fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.6.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "1.2.2"
    apt:
      repo: "puppetlabs/apt"
      ref: "1.8.0"
    postgresql:
      repo: "puppetlabs/postgresql"
      ref: "4.3.0"
  symlinks:
    repmgr: "#{source_dir}"
